'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { CalendarMinus, CalendarPlus, Plus } from 'lucide-react'
import { Button, Card, Dialog, Input } from '@/components/ui'

type Workout = { id: string; dayNumber: number; scheduledDate: string | Date; entries: unknown[] }

export function GymWeekView({ weekId, workouts, canEdit }: { weekId: string; workouts: Workout[]; canEdit: boolean }) {
  const router = useRouter(); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [open, setOpen] = useState(false); const [removeOpen, setRemoveOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null)
  const sorted = [...workouts].sort((a, b) => a.dayNumber - b.dayNumber); const last = sorted[sorted.length - 1]
  async function addDay(scheduledDate: string) { setLoading(true); setError(null); try { const response = await fetch(`/api/gym/weeks/${weekId}/workouts`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scheduledDate }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? 'Не удалось добавить день'); setOpen(false); router.refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка') } finally { setLoading(false) } }
  async function removeLastDay() { if (!last) return; setLoading(true); try { const response = await fetch(`/api/gym/workouts/${last.id}`, { method: 'DELETE' }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? 'Не удалось удалить день'); setRemoveOpen(false); router.refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка') } finally { setLoading(false) } }
  return <><div className="flex flex-wrap justify-end gap-2">{canEdit && <><Button variant="outline" size="sm" onClick={() => setOpen(true)}><Plus className="h-4 w-4"/> Добавить день</Button>{sorted.length === 3 && last && <Button variant="outline" size="sm" disabled={loading} onClick={() => void addDay(new Date(new Date(last.scheduledDate).getTime() + 86400000).toISOString().slice(0, 10))}><CalendarPlus className="h-4 w-4"/> Перейти на 4 дня</Button>}{sorted.length === 4 && <Button variant="outline" size="sm" onClick={() => setRemoveOpen(true)}><CalendarMinus className="h-4 w-4"/> Перейти на 3 дня</Button>}</>}</div>{error && <p className="text-sm text-danger">{error}</p>}<div className="grid gap-4 lg:grid-cols-3">{sorted.map((workout) => <Link key={workout.id} href={`/gym/workouts/${workout.id}`}><Card className="min-h-40 hover:border-accent"><h2 className="font-display uppercase">День {workout.dayNumber}</h2><p className="text-xs text-text-secondary">{new Date(workout.scheduledDate).toISOString().slice(0, 10)}</p><p className="mt-8 text-sm text-text-secondary">{workout.entries.length} упражнений</p></Card></Link>)}</div><Dialog open={open} onOpenChange={setOpen} title="Новый день" description="Выберите дату тренировки."><div className="space-y-3"><Input type="date" value={date} onChange={(e) => setDate(e.target.value)}/><div className="flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => setOpen(false)}>Отмена</Button><Button size="sm" disabled={loading || !date} onClick={() => void addDay(date)}>{loading ? 'Добавляю…' : 'Добавить'}</Button></div></div></Dialog><Dialog open={removeOpen} onOpenChange={setRemoveOpen} title="Убрать последний день?" description="День и все упражнения внутри него будут удалены."><div className="flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => setRemoveOpen(false)}>Отмена</Button><Button variant="danger" size="sm" disabled={loading} onClick={() => void removeLastDay()}>{loading ? 'Удаляю…' : 'Убрать'}</Button></div></Dialog></>
}
